- name: Get sudo users
  hosts: all
  vars: 
    - userlist: "{{ lookup('hashi_vault', 'secret=userlist/data/{{ ansible_hostname }}') }}"
  tasks:
    - name: Get list of sudo users
      register: existingusers
      shell: 
        cmd: cut -d ':' -f1,3 /etc/passwd | egrep ':[0-9]{4}$' | cut -d ':' -f1
     
    - name: Add the user 'james' with a bash shell, appending the group 'admins' and 'developers' to the user's groups
      debug: 
        var: existingusers.stdout_lines 
        
    - name: Get {{ ansible_hostname }} user list
      debug:
        var: userlist.data.list
        
        
    - name: Comprobar que no existen usuarios no deseados     
      fail: 
        msg: "Usuario {{item}} no debería existir"
      with_items: "{{existingusers.stdout_lines}}"
      when: "{{item}}" not in "{{userlist.data.list.split(',')}}"
