- name: Detección de cuentas
  hosts: all
  vars: 
    - userlist: "{{ lookup('hashi_vault', 'secret=userlist/data/{{ ansible_hostname }}') }}"
  tasks:
    - name: Obtener lista de usuarios
      register: existingusers
      shell: 
        cmd: cut -d ':' -f1,3 /etc/passwd | egrep ':[0-9]{4}$' | cut -d ':' -f1
     
    - name: Mostrar lista de usuarios existentes en el equipo
      debug: 
        var: existingusers.stdout_lines 
        
    - name: Mostrar lista de usuarios de confianza en equipo {{ ansible_hostname }} 
      debug:
        var: userlist.data.list

    - name: Eliminar usuario no registrado
      become: yes
      user: 
        name: "{{item}}"
        state: absent
        remove: yes
      when: "{{ item not in lookup('list', userlist.data.list.split(',')) }}" 
      with_items: "{{existingusers.stdout_lines}}"
      
    - fail:
        msg: El usuario "{{item}}" no es de confianza.
      when: "{{ item not in lookup('list', userlist.data.list.split(',')) }}" 
      with_items: "{{existingusers.stdout_lines}}"
