---
- hosts: "{{host_ip}}"
  vars:
     userlist: "{{ lookup('hashi_vault', 'secret=userlist/data/{{ ansible_hostname }}') }}"
     newuserlist: "{{userlist.data.list}},{{username}}"
  become: true
  tasks:
    - name: Crear usuario "{{username}}" en equipo "{{ansible_hostame}}"
      user:
        name: "{{username}}"
        password: "{{ password | password_hash('sha512') }}"
        
    - name: Expiring password for user "{{ username }}"
      shell: chage -d 0 "{{ username }}"
      
    - name: Añadir usuario a lista de usuarios de confianza
      uri:
        url: "http://192.168.0.16:8200/v1/userlist/data/{{ ansible_hostname }}"
        method: POST
        body: '{"data": {"list":"{{newuserlist}}"}}'
        body_format: json
        validate_certs: no
        headers:
          X-Vault-Token: "{{ vault_token }}"
        
