- name: Revocación de privilegios
  hosts: all
  tasks:
  
    - name: Obtener lista de usuarios de administración
      register: sudousers
      shell: 
        cmd: getent group sudo | cut -d ':' -f4
     
    - name: Eliminar usuarios de grupo de administración
      become: true
      user:
        name: "{{ item }}"
        groups: ''
      with_items: "{{ sudousers.stdout.split(',') }}"
      when: sudousers.stdout != ""
