- name: Get privileged account credentials
  hosts: 
    "{{host_ip}}"
  tasks:
    - name: Get {{ ansible_hostname }} privileged credentials
      debug:
        msg: "{{ lookup('hashi_vault', 'secret=securecreds/data/{{ ansible_hostname }}') }}"
