- name: Get sudo users
  hosts: all
  tasks:
    - name: Get list of sudo users
      register: sudousers
      shell: 
        cmd: getent group sudo 
      
    - local_action: command echo "{{ item }}"
      with_items: "{{ sudousers.stdout_lines }}"
      
    - name: 
      debug:
        var: sudousers
     #   msg: "{{ sudousers.stdout_lines.split(",")[0] }}"
