- name: Get sudo users
  hosts: all
  tasks:
    - name: Get list of sudo users
      register: sudousers
      shell: 
        cmd: getent group sudo | cut -d ':' -f4
     
    - name: Add the user 'james' with a bash shell, appending the group 'admins' and 'developers' to the user's groups
      user:
        name: "{{ item }}"
        groups: ''
      with_items: "{{ sudousers.stdout.split(',') }}"

    - name: 
      debug:
        #var: sudousers
        msg: "{{ sudousers.stdout.split(',') }}"
