- name: Get sudo users
  hosts: all
  tasks:
    - name: Get list of sudo users
      register: sudousers
      shell: 
        cmd: getent group sudo 
      
      
    - name: 
      debug:
        msg: "{{  sudousers.stdout_lines.split(":")[0] | lower }}"
