- name: Get sudo users
  hosts: all
  tasks:
    - name: Get list of sudo users
      register: sudousers
      shell: 
        cmd: getent group sudo 
      
      
    - name: 
      debug:
        msg: sudousers
