- name: Get sudo users
  hosts: all
  tasks:
    - name: Get list of sudo users
      shell: 
        cmd: |
        getent group sudo | cut -d\":\" -f4
      register: sudousers
      
    - name: 
      debug:
        msg: sudousers
