- name: Get privileged account credentials
  hosts: 
    "{{host_ip}}"
  tasks:
    - name: Get {{ host_ip }} privileged credentials
      debug:
        msg: "{{ lookup('hashi_vault', 'secret=securecreds/data/awx-debian') }}"
