---
- hosts: all
  become: yes
  vars:
    sudoers: awxprueba
  tasks:
    - name: Make sure we have a 'sudo' group
      group:
        name: sudo
        state: present

    - name: Allow 'sudo' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD:ALL'
        validate: visudo -cf %s

    - getent: database=passwd key="{{ sudoers }}"

    - name: Add sudoers user to sudo group
      user:
        name: "{{ sudoers }}"
        groups: sudo
        append: yes

