---
- hosts: "{{host_ip}}"
  become: yes
  vars:
    sudoers: "{{username}}"
    
  tasks:
    - name: Comprobar que existe el grupo de administraci칩n
      group:
        name: sudo
        state: present

    - name: Garantizar permisos de administraci칩n
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL)'
        validate: visudo -cf %s

    - name: Comprobar que existe el usuario en el equipo.
      getent: database=passwd key="{{ sudoers }}"

    - name: A침adir usuario al grupo de administraci칩n
      user:
        name: "{{ sudoers }}"
        groups: sudo
        append: yes

