- name: Ocultación
  hosts: all
  vars: 
    - password: "{{ lookup('hashi_vault', 'secret=securecreds/data/{{ ansible_hostname }}') }}"
    - ansible_become_password: password.data.password
  tasks:      
    - name: Mostrar contraseña {{ ansible_hostname }} 
      debug:
        var: ansible_become_password
