---
- name: Rotar credenciales privilegiadas
  hosts: all
  tasks:
    - name: Obtener una contraseña random
      debug:
        msg: "{{ lookup('password', '/dev/null  length=12 chars=ascii_letters,digits,hexdigits,punctuation') }}"
      
      
     
  
  
    - name: Save a secret on Vault
      uri:
        url: "http://192.168.0.16:8200/v1/securecreds/data/prueba"
        method: POST
        body: '{"data": {"pass":"holi"}}'
        body_format: json
        validate_certs: no
        headers:
          X-Vault-Token: s.ntTcsG8swHI9Xdhw0KtXDKsv
