---
- name: Rotar credenciales privilegiadas
  hosts: all
  vars: 
    #ansible_become_user: "{{ lookup('hashi_vault', 'secret=securecreds/data/{{ ansible_hostname }}:username') }}"
    #ansible_become_password: "{{ lookup('hashi_vault', 'secret=securecreds/data/{{ ansible_hostname }}:password') }}"
    newpassword: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,hexdigits,punctuation') }}"
  tasks:
    - name: Get sudo username
      debug:
        msg: "{{ lookup('hashi_vault', 'secret=securecreds/data/{{ ansible_hostname }}') }}"
        
    - name: Get sudo pass
      debug:
        msg: "{{ lookup('hashi_vault', 'secret=securecreds/data/{{ ansible_hostname }}/data') }}"
        
   # - name: Guardar nueva contraseña en Vault
   #   uri:
   #     url: "http://192.168.0.16:8200/v1/securecreds/data/prueba"
   #     method: POST
   #     body: '{"data": {"password":"{{newpassword}}"}}'
   #     body_format: json
   #     validate_certs: no
   #     headers:
   #       X-Vault-Token: s.ntTcsG8swHI9Xdhw0KtXDKsv
          
    #- name: Rotar contraseña de root
    #  become: yes
    #  user: 
    #      name: "{{ansible_become_user}}"
    #      password: "{{ newpassword | password_hash('sha512') }}"
      
