---
- name: Rotar credenciales privilegiadas
  hosts: localhost
  tasks:
    - name: Save a secret on Vault
      uri:
        url: "http://192.168.0.16:8200/v1/securecreds/data/prueba"
        method: POST
        body: '{"data": {"pass":"holi"}}'
        body_format: json
        validate_certs: no
        headers:
          X-Vault-Token: s.ntTcsG8swHI9Xdhw0KtXDKsv
