---
- name: Rotar credenciales privilegiadas
  hosts: all
  become: yes
  vars: 
    #ansible_become_user: "{{ jsonVar | from_json | json_query('queue.[0].['color']')}}"
    #ansible_become_password: "{{ lookup('hashi_vault', 'secret=securecreds/data/{{ ansible_hostname }}:password') }}"
    #hello: "{{ lookup('hashi_vault', 'secret=securecreds/data/hola:prueba')}}"
    newpassword: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,hexdigits,punctuation') }}"
    prueba: "Prueba2!"
  tasks:
    #- name: Get sudo username
    #  uri:
    #    url: "http://192.168.0.16:8200/v1/securecreds/data/awx-debian"
    #    method: GET
    #    body_format: json
    #    validate_certs: no
    #    headers:
    #      X-Vault-Token: s.ntTcsG8swHI9Xdhw0KtXDKsv
    #  register: prueba    
      
    - name: Resultado  
      debug:
        msg: "{{newpassword}}"
        
   # - name: Get sudo pass
   #   debug:
   #     msg: "{{ lookup('hashi_vault', 'secret=securecreds/data/{{ ansible_hostname }}/data') }}"
        
   # - name: Guardar nueva contraseña en Vault
   #   uri:
   #     url: "http://192.168.0.16:8200/v1/securecreds/data/prueba"
   #     method: POST
   #     body: '{"data": {"password":"{{newpassword}}"}}'
   #     body_format: json
   #     validate_certs: no
   #     headers:
   #       X-Vault-Token: s.ntTcsG8swHI9Xdhw0KtXDKsv
   
    - name: Resultado  
      debug:
        msg: "{{prueba}}"
    - name: Rotar contraseña de root
      become: yes
      user: 
        name: meri
        update_password: always
        password: "{{ prueba | password_hash('sha512') }}"
        
    - name: Guardar nueva contraseña en Vault
      uri:
        url: "http://192.168.0.16:8200/v1/securecreds/data/hola"
        method: POST
        body: '{"data": {"prueba":"{{prueba}}"}}'
        body_format: json
        validate_certs: no
        headers:
          X-Vault-Token: s.ntTcsG8swHI9Xdhw0KtXDKsv
