---
- name: Rotar credenciales privilegiadas
  hosts: all
  become: yes
  vars: 
    #ansible_become_user: "{{ jsonVar | from_json | json_query('queue.[0].['color']')}}"
    #ansible_become_password: "{{ lookup('hashi_vault', 'secret=securecreds/data/{{ ansible_hostname }}:password') }}"
    #hello: "{{ lookup('hashi_vault', 'secret=securecreds/data/hola:prueba')}}"

  tasks: 
    - set_fact:
        newpassword: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,hexdigits,punctuation') }}"
  
  
    - name: Rotar contraseña de root
      become: yes
      user: 
        name: meri
        update_password: always
        password: "{{ newpassword | password_hash('sha512') }}"
        
    - name: Guardar nueva contraseña en Vault
      uri:
        url: "http://192.168.0.16:8200/v1/securecreds/data/{{ ansible_hostname }}"
        method: POST
        body: '{"password": {"prueba":"{{newpassword}}"}}'
        body_format: json
        validate_certs: no
        headers:
          X-Vault-Token: s.8uHQcSb3fDvCmmYItdh4BQMT
