---
- name: Rotar credenciales privilegiadas
  hosts: all
  vars: 
    current_password: "{{ lookup('hashi_vault', 'secret=securecreds/data/{{ ansible_hostname }}') }}"
    newpassword: "{{ lookup('password', '/dev/null  length=12 chars=ascii_letters,digits,hexdigits,punctuation') }}"
  tasks:
  
    - name: Get {{ ansible_hostname }} privileged credentials
      debug:
        msg: current_password

    - name: Save a secret on Vault
      uri:
        url: "http://192.168.0.16:8200/v1/securecreds/data/prueba"
        method: POST
        body: '{"data": {"password":"{{newpassword}}"}}'
        body_format: json
        validate_certs: no
        headers:
          X-Vault-Token: s.ntTcsG8swHI9Xdhw0KtXDKsv
