- name: Set password complexity
  hosts: all
  tasks:
  - name: Change password time expiration
    lineinfile:
      path: /etc/login.defs
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - { regexp: '^PASS_MAX_DAYS *[0-9]*' , line: PASS_MAX_DAYS 2 }
      - { regexp: '^PASS_MIN_DAYS *[0-9]*' , line: PASS_MIN_DAYS 0 }
      - { regexp: '^PASS_WARN_AGE *[0-9]*' , line: PASS_WARN_AGE 3 }
    become: true

  - name: Install password complexity checking package
    package:
      name: libpam-pwquality
      state: present
    become: true
    
  - name: Change password complexity
    lineinfile:
      path: /etc/pam.d/common-password
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - { regexp: '^password *requisite *pam_pwquality.so.*' , line: password requisite pam_pwquality.so retry=3 minlen=8 difok=3 lcredit=-1 ucredit=-1 dcredit=-1 ocredit=-1 reject_username enforce_for_root }
    become: true
