- name: Set password complexity
  hosts: all
  tasks:
  - name: Change line
    lineinfile:
      path: /home/maria/ansible/PAM/script.defs
      regexp: '^PASS_MAX_DAYS *[0-9]*'
      line: PASS_MAX_DAYS 3
