- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
    - name: install hvac pip package
      become: yes
      become_method: sudo
      pip:
        name: ansible-modules-hashivault
        state: present
      delegate_to: localhost
        
    - name: localhost ip?
      debug: var=ansible_all_ipv4_addresses
      delegate_to: localhost
      
    - name: localhost OS?
      debug:
        msg: "{{ hostvars[inventory_hostname].ansible_distribution }}"
      delegate_to: localhost
      
    - name: Get username
      debug:
        msg: '{{ ansible_user }}'
